# Generated by Django 5.2.1 on 2025-06-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nopreserveroot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
